FROM node:12

# Create app directory
RUN mkdir /app1
WORKDIR /app1

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json /app1/

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . /app1

ENV NODE_ENV QA
ENV PORT 8080

EXPOSE 8080

CMD [ "node", "server.js" ]